version: "3"

services:
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.0
    restart: always
    ports:
      - "8080:8080"
    environment:
      # see https://github.com/mediagis/nominatim-docker/tree/master/4.0#configuration for more options
      PBF_URL: https://download.geofabrik.de/north-america/us-south-latest.osm.pbf
      NOMINATIM_PASSWORD: very_secure_password
    volumes:
      - nominatim-data:/var/lib/postgresql/12/main
    shm_size: 1gb

volumes:
  nominatim-data: